spells = [
  'Alarm',
  'Animal Friendship',
  'Bane',
  'Bless',
  'Burning Hands',
  'Charm Person',
  'Color Spray',
  'Command',
  'Comprehend Languages',
  'Create or Destroy Water',
  'Cure Wounds',
  'Detect Evil and Good',
  'Detect Magic',
  'Detect Poison and Disease',
  'Disguise Self',
  'Divine Favor',
  'Entangle',
  'Expeditious Retreat',
  'Faerie Fire',
  'False Life',
  'Feather Fall',
  'Find Familiar',
  'Floating Disk',
  'Fog Cloud',
  'Goodberry',
  'Grease',
  'Guiding Bolt',
  'Healing Word',
  'Hellish Rebuke',
  'Heroism',
  'Hideous Laughter',
  "Hunter's Mark",
  'Identify',
  'Illusory Script',
  'Inflict Wounds',
  'Jump',
  'Longstrider',
  'Mage Armor',
  'Magic Missile',
  'Protection from Evil and Good',
  'Purify Food and Drink',
  'Sanctuary',
  'Shield',
  'Shield of Faith',
  'Silent Image',
  'Sleep',
  'Speak with Animals',
  'Thunderwave',
  'Unseen Servant',
  'Acid Arrow',
  'Aid',
  'Alter Self',
  'Animal Messenger',
  'Arcane Lock',
  "Arcanist's Magic Aura",
  'Augury',
  'Barkskin',
  'Blindness/Deafness',
  'Blur',
  'Branding Smite',
  'Calm Emotions',
  'Continual Flame',
  'Darkness',
  'Darkvision',
  'Detect Thoughts',
  'Enhance Ability',
  'Enlarge/Reduce',
  'Enthrall',
  'Find Steed',
  'Find Traps',
  'Flame Blade',
  'Flaming Sphere',
  'Gentle Repose',
  'Gust of Wind',
  'Heat Metal',
  'Hold Person',
  'Invisibility',
  'Knock',
  'Lesser Restoration',
  'Levitate',
  'Locate Animals or Plants',
  'Locate Object',
  'Magic Mouth',
  'Magic Weapon',
  'Mirror Image',
  'Misty Step',
  'Moonbeam',
  'Pass without Trace',
  'Prayer of Healing',
  'Protection from Poison',
  'Ray of Enfeeblement',
  'Rope Trick',
  'Scorching Ray',
  'See Invisibility',
  'Shatter',
  'Silence',
  'Spider Climb',
  'Spike Growth',
  'Spiritual Weapon',
  'Suggestion',
  'Warding Bond',
  'Web',
  'Zone of Truth',
  'Animate Dead',
  'Beacon of Hope',
  'Bestow Curse',
  'Blink',
  'Call Lightning',
  'Clairvoyance',
  'Conjure Animals',
  'Counterspell',
  'Create Food and Water',
  'Daylight',
  'Dispel Magic',
  'Fear',
  'Fireball',
  'Fly',
  'Gaseous Form',
  'Glyph of Warding',
  'Haste',
  'Hypnotic Pattern',
  'Lightning Bolt',
  'Magic Circle',
  'Major Image',
  'Mass Healing Word',
  'Meld into Stone',
  'Nondetection',
  'Phantom Steed',
  'Plant Growth',
  'Protection from Energy',
  'Remove Curse',
  'Revivify',
  'Sending',
  'Sleet Storm',
  'Slow',
  'Speak with Dead',
  'Speak with Plants',
  'Spirit Guardians',
  'Stinking Cloud',
  'Tiny Hut',
  'Tongues',
  'Vampiric Touch',
  'Water Breathing',
  'Water Walk',
  'Wind Wall',
]
